timezone: Asia/Tokyo
strict_front_matter: true
permalink: pretty
include: ['topics']
url: "https://is-america-great-yet.com"
plugins:
  - jekyll-sitemap
description: "MAGA leads to an evaluatory counter-question: Is America Great Yet? Unfortunately, the current answer is no."